# Generated by Django 4.1.7 on 2023-04-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalExpenses', '0018_alter_userexpense_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexpense',
            name='monthly_cellphone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userexpense',
            name='monthly_child_care',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userexpense',
            name='monthly_entertainment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userexpense',
            name='monthly_food_expenses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userexpense',
            name='monthly_health_care',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userexpense',
            name='monthly_home_rent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userexpense',
            name='monthly_internet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userexpense',
            name='monthly_loan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userexpense',
            name='monthly_pet_care',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userexpense',
            name='monthly_retirement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userexpense',
            name='monthly_travel_expenses',
            field=models.IntegerField(default=0),
        ),
    ]
